spring:
  profiles:
    default: monolith
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/brokerx_monolith}
    username: ${DB_USERNAME:brokerx}
    password: ${DB_PASSWORD:brokerx}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      repositories:
        enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 10
        enable.idempotence: true
  mail:
    host: ${BROKERX_SMTP_HOST:}
    port: ${BROKERX_SMTP_PORT:587}
    username: ${BROKERX_SMTP_USERNAME:}
    password: ${BROKERX_SMTP_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: brokerx
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4317}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

brokerx:
  security:
    jwt-secret: ${BROKERX_JWT_SECRET:change-me-change-me-change-me-123456}
    jwt-expiration-seconds: ${BROKERX_JWT_EXPIRATION_SECONDS:3600}
  mail:
    enabled: ${BROKERX_MAIL_ENABLED:false}
    from: ${BROKERX_MAIL_FROM:no-reply@brokerx.dev}
    to-override: ${BROKERX_MAIL_TO_OVERRIDE:}
    expose-otp-response: ${BROKERX_MAIL_EXPOSE_OTP_RESPONSE:false}

---
spring:
  config:
    activate:
      on-profile: auth
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/brokerx_auth}

---
spring:
  config:
    activate:
      on-profile: portfolio
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/brokerx_portfolio}

---
spring:
  config:
    activate:
      on-profile: orders
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/brokerx_orders}
